// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXQ4o55g3jwiKYf0vg0K9_Km_wzheZQyI',
    appId: '1:391105067665:web:2e03271c223dc1ca469d30',
    messagingSenderId: '391105067665',
    projectId: 'tugas2-b9b15',
    authDomain: 'tugas2-b9b15.firebaseapp.com',
    storageBucket: 'tugas2-b9b15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4NV0sBlzUnzTBHxBg8nRE-Ch9gDaA8Fg',
    appId: '1:391105067665:android:cd5db261c732a2cf469d30',
    messagingSenderId: '391105067665',
    projectId: 'tugas2-b9b15',
    storageBucket: 'tugas2-b9b15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn3bbialThzqchiB1mVw5skCEL64MFSkc',
    appId: '1:391105067665:ios:8e41922067d8635c469d30',
    messagingSenderId: '391105067665',
    projectId: 'tugas2-b9b15',
    storageBucket: 'tugas2-b9b15.appspot.com',
    iosBundleId: 'com.example.tugas2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn3bbialThzqchiB1mVw5skCEL64MFSkc',
    appId: '1:391105067665:ios:8e41922067d8635c469d30',
    messagingSenderId: '391105067665',
    projectId: 'tugas2-b9b15',
    storageBucket: 'tugas2-b9b15.appspot.com',
    iosBundleId: 'com.example.tugas2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXQ4o55g3jwiKYf0vg0K9_Km_wzheZQyI',
    appId: '1:391105067665:web:b5b2421a73f5e364469d30',
    messagingSenderId: '391105067665',
    projectId: 'tugas2-b9b15',
    authDomain: 'tugas2-b9b15.firebaseapp.com',
    storageBucket: 'tugas2-b9b15.appspot.com',
  );
}
